# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RacingCarGame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'RealmSwift'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  # Pods for RacingCarGame

end
